# ワークフロー名
name: butler
on:
  workflow_dispatch:
  schedule:
    # 定期実行する時間・・・①
    - cron: '0 22 * * *'
    
jobs:
  build:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Scripts

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          # 必要なパッケージインストール・・・②
          pip install slack_sdk
          pip install pathlib
      - name: pwd
        run: pwd
      - name: lsCommand
        run: ls -a
      - name: lsCommandInData
        run: cd ./
      - name: ls
        run: ls -a
          
      - name: Run script
        run: |
          # 定期実行するファイルを指定。・・・③
          python Butler_Slack.py ${{secrets.SLACK_BOT_TOKEN}} ${{secrets.CHANNEL_ID}}
